project:
  output-dir: tmp/part
  resources:
    - code/data/interval-estimation-calc.ods
    - code/data/empirical-distribution-calc.ods
    - code/data/order-processing-times.csv
    - "!tmp/**"

book:
  chapters:
    - index.qmd
    - part: "Случайные события как качественная сторона случайных явлений в бизнесе"
      chapters:
        - book/chapters/01-random-events/01-frequency-and-probability.qmd
        - book/chapters/01-random-events/02-multiplication-and-addition-theorems.qmd
        - book/chapters/01-random-events/03-repeated-trials.qmd
        - book/chapters/01-random-events/04-total-probability-and-bayes.qmd
        - book/chapters/01-random-events/05-interval-estimation.qmd
        - book/chapters/01-random-events/06-frequency-calculation-libreoffice.qmd
        - book/chapters/01-random-events/07-self-check.qmd
        - book/chapters/01-random-events/08-test-tasks.qmd
    - part: "Данные статистики продаж - случайные величины как количественная сторона случайных явлений"
      chapters:
        - book/chapters/02-sales-statistics/01-sales-statistics.qmd
        - book/chapters/02-sales-statistics/02-distribution-law.qmd
        - book/chapters/02-sales-statistics/03-moments-and-characteristics.qmd
        - book/chapters/02-sales-statistics/04-discrete-distributions.qmd
        - book/chapters/02-sales-statistics/05-continuous-distributions.qmd
        - book/chapters/02-sales-statistics/06-distribution-plots.qmd
        - book/chapters/02-sales-statistics/07-descriptive-statistics.qmd
        - book/chapters/02-sales-statistics/08-self-check.qmd
    - references.qmd
