project:
  type: book
  resources:
    - code/data/interval-estimation-calc.ods
    - "!tmp/**"

profile:
  default: full

lang: ru

toc: true
toc-title: "Содержание"
toc-depth: 3

number-sections: true
number-depth: 3
crossref:
  fig-title: "Рисунок"
  tbl-title: "Таблица"
  eq-title: "Формула"
  fig-prefix: "рис."
  tbl-prefix: "табл."
  eq-prefix: "формула"
  exm-title: "Пример"
  exm-prefix: "пример"

book:
  title: "Теория вероятностей и математическая статистика для начинающих IT-предпринимателей"
  subtitle: "Под редакцией П.С. Ткачева"
  page-navigation: true
  repo-url: https://github.com/vshp-online/ps-it-book
  output-file: probability-statistics-for-it-entrepreneurs

  author:
    - "Н.Н. Зубов"
    - "П.С. Ткачев"
    - "С.З. Умаров"

bibliography: references.bib
nocite: '@*'

format:
  html:
    toc: true
    number-sections: true
    code-copy: true
    anchor-sections: true
    smooth-scroll: true
    css: book/styles/book.css
  pdf:
    pdf-engine: lualatex
    documentclass: scrbook
    classoption:
      - open=any
    papersize: a4
    fontsize: 14pt

    mainfont: "Libertinus Serif"
    sansfont: "Libertinus Sans"
    monofont: "Libertinus Mono"
    mathfont: "Libertinus Math"

    geometry:
      - margin=25mm
    number-sections: true
    include-in-header:
      - book/tex/typography.tex
      - book/tex/hyphenation.tex

execute:
  freeze: auto
