project:
  type: book
  resources:
    - code/data/interval-estimation-calc.ods

lang: ru

toc: true
toc-title: "Содержание"
toc-depth: 3

number-sections: true
number-depth: 3
crossref:
  fig-title: "Рисунок"
  tbl-title: "Таблица"
  eq-title: "Формула"
  fig-prefix: "рис."
  tbl-prefix: "табл."
  eq-prefix: "формула"
  exm-title: "Пример"
  exm-prefix: "пример"

book:
  title: "Теория вероятностей и математическая статистика для начинающих IT-предпринимателей"
  subtitle: "Под редакцией П.С. Ткачева"
  page-navigation: true
  repo-url: https://github.com/vshp-online/ps-it-book
  output-file: probability-statistics-for-it-entrepreneurs

  author:
    - "Н.Н. Зубов"
    - "П.С. Ткачев"
    - "С.З. Умаров"
  chapters:
    - index.qmd
    - part: "Случайные события как качественная сторона случайных явлений в бизнесе"
      chapters:
        - book/chapters/01-random-events/01-frequency-and-probability.qmd
        - book/chapters/01-random-events/02-multiplication-and-addition-theorems.qmd
        - book/chapters/01-random-events/03-repeated-trials.qmd
        - book/chapters/01-random-events/04-total-probability-and-bayes.qmd
        - book/chapters/01-random-events/05-interval-estimation.qmd
        - book/chapters/01-random-events/06-frequency-calculation-libreoffice.qmd
        - book/chapters/01-random-events/07-self-check.qmd
        - book/chapters/01-random-events/08-test-tasks.qmd
    - part: "Данные статистики продаж - случайные величины как количественная сторона случайных явлений"
      chapters:
        - book/chapters/02-sales-statistics/01-sales-statistics.qmd
    - part: "Использование методов математической статистики в бизнесе"
      chapters:
        - book/chapters/03-statistical-methods/01-statistical-methods.qmd
    - part: "Выявление и оценка связи между признаками"
      chapters:
        - book/chapters/04-associations/01-associations.qmd
    - part: "Динамические ряды и методы их анализа в бизнесе"
      chapters:
        - book/chapters/05-time-series-analysis/01-time-series-analysis.qmd
    - references.qmd

bibliography: references.bib
nocite: '@*'

format:
  html:
    toc: true
    number-sections: true
    code-copy: true
    anchor-sections: true
    smooth-scroll: true
    css: book/styles/book.css
  pdf:
    pdf-engine: lualatex
    documentclass: scrbook
    classoption:
      - open=any
    papersize: a4
    fontsize: 14pt

    mainfont: "Libertinus Serif"
    sansfont: "Libertinus Sans"
    monofont: "Libertinus Mono"
    mathfont: "Libertinus Math"

    geometry:
      - margin=25mm
    number-sections: true
    include-in-header:
      - book/tex/typography.tex
      - book/tex/hyphenation.tex

execute:
  freeze: auto
