project:
  type: default
  output-dir: tmp/check
  resources:
    - code/data/interval-estimation-calc.ods
    - code/data/monthly-orders-time-series.csv
    - code/data/monthly-orders-forecast-evaluation.csv
    - code/data/monthly-orders-forecast-calc.ods
    - "!tmp/**"
